name: Render Rmd

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "knitr", "ggplot2", "readr", "dplyr", "lubridate"))'
      - name: Render Rmd
        run: |
          Rscript -e 'rmarkdown::render("Capstone_Report.Rmd")'
