name: Test Minimal Workflow

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello GitHub Actions!"
      - name: Upload dummy file
        run: echo "This is a test" > test.txt
      - uses: actions/upload-artifact@v3
        with:
          name: dummy-artifact
          path: test.txt
