name: Render Rmd

on:
  push:
    branches: [main]
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install Pandoc and system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc build-essential \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libgdal-dev libgeos-dev libproj-dev
      - name: Install packages
        run: |
          Rscript -e 'install.packages(c(
            "remotes", "devtools",
            "readr", "dplyr", "ggplot2", "scales",
            "tibble", "stringr", "purrr", "gridExtra", "zoo",
            "lubridate", "tidyr", "knitr", "rmarkdown"
          ))'
      - name: Diagnostic usmap install with verbose log
        run: |
          Rscript -e 'install.packages("usmap", dependencies=TRUE, repos="https://cloud.r-project.org")'
          Rscript -e 'cat("------\\nINSTALLED PACKAGES:\\n------\\n"); print(installed.packages()[,"Package"])'
      - name: Render Rmd
        run: |
          Rscript -e 'rmarkdown::render("analysis/Capstone_Report.Rmd", quiet = FALSE)'
